Add config files for mellanox-mlnxen and intel-e1000e
ydirson/driver-disks pull request #1
Opened 2023-12-05 09:34 UTC by gduperrey

Modify the cfg fil for intel-e1000e
Add the cfg file for mellanox-mlnxen

2023-12-12 16:35 UTC, stormi requested changes
The commit title says "add" but only one is added, the other one is modified. 

Ideally, there should be one commit modifying the key name in existing files, and another commit which adds the new one.

2023-12-12 16:35 UTC, stormi commented on intel-e1000e-alt-8.2.cfg
> +GPG_PUBKEY_FILE="RPM-GPG-KEY-XS-DDK-SingleUse"
We probably don't need XS DDK in the key name.

```suggestion
GPG_PUBKEY_FILE="RPM-GPG-KEY-XCP-SingleUse"
```

2023-12-12 16:35 UTC, stormi commented on mellanox-mlnxen-alt-8.2.cfg
> +PACK_DESC="Driver Pack for Intel e1000e device driver"
Wrong description, this is mellanox mlnxen.

2023-12-14 14:51 UTC, gduperrey commented
And here is it with two separate commits.

2023-12-14 15:53 UTC, stormi approved these changes

2023-12-14 15:54 UTC, merged